import pandas as pd
import csv

# Expanded dictionary of 5-letter French words and their Tamil translations
french_tamil_dict = {
    "merci": "நன்றி",
    "moins": "குறைய",
    "livre": "புத்தக",
    "rouge": "சிவப்பு",
    "chien": "நாய்கள்",
    "heure": "நேரம்",
    "blanc": "வெள்ளை",
    "coeur": "இதயம்",
    "salon": "அறை",
    "table": "மேசை",
    "pomme": "ஆப்பிள்",
    "plage": "கடற்க",
    "monde": "உலகம்",
    "noire": "கருப்பு",
    "jaune": "மஞ்சள்",
    "sucre": "சர்க்க",
    "froid": "குளிர்",
    "chaud": "வெப்ப",
    "train": "ரயில்",
    "porte": "கதவு",
    "marié": "திருமண",
    "solei": "சூரிய",
    "nuage": "மேகம்",
    "fleur": "மலர்",
    "arbre": "மரம்",
    "sable": "மணல்",
    "ville": "நகரம்",
    "place": "இடம்",
    "ferme": "பண்ணை",
    "herbe": "புல்",
    "pluie": "மழை",
    "neige": "பனி",
    "vague": "அலை",
    "calme": "அமைதி",
    "piano": "பியானோ",
    "image": "படம்",
    "voile": "திரை",
    "roche": "பாறை",
    "verre": "கண்ணா",
    "bruit": "சத்தம்",
    # Additional words
    "carte": "அட்டை",
    "boite": "பெட்டி",
    "champ": "வயல்",
    "classe": "வகுப்பு",
    "danse": "நடனம்",
    "doigt": "விரல்",
    "ecole": "பள்ளி",
    "etoil": "நட்சத்",
    "feuil": "இலை",
    "foret": "காடு",
    "fruit": "பழம்",
    "glace": "பனி",
    "grain": "தானிய",
    "habit": "ஆடை",
    "hotel": "விடுதி",
    "idole": "சிலை",
    "jouet": "விளைய",
    "lance": "வேல்",
    "lueur": "ஒளி",
    "matin": "காலை",
    "metal": "உலோக",
    "miner": "சுரங்க",
    "nuque": "கழுத்து",
    "odeur": "வாசனை",
    "ongle": "நகம்",
    "ortie": "காய்",
    "panne": "பழுது",
    "pâtes": "பாஸ்த",
    "peche": "மீன்",
    "phare": "விளக்கு",
    "piste": "பாதை",
    "plume": "இறகு",
    "poche": "பை",
    "poele": "வாணலி",
    "point": "புள்ளி",
    "porte": "கதவு",
    "poste": "அஞ்சல்",
    "prise": "பிடி",
    "radio": "வானொலி",
    "reine": "ராணி",
    "repos": "ஓய்வு",
    "ronde": "வட்டம்",
    "sable": "மணல்",
    "sante": "உடல்",
    "serre": "பூங்கா",
    "sirop": "பானம்",
    "soupe": "சூப்",
    "stylo": "பேனா",
    "tapis": "விரிப்பு",
    "tente": "கூடார",
    "terre": "பூமி",
    "tigre": "புலி",
    "toile": "துணி",
    "tombe": "கல்லற",
    "usine": "தொழிற்",
    "vague": "அலை",
    "valve": "வால்வு",
    "veine": "நரம்பு",
    "vente": "விற்ப",
    "verbe": "வினை",
    "verre": "கண்ணா",
    "vitre": "ஜன்னல்",
    "voile": "திரை",
    "voute": "வளைவு",
    "wagon": "பெட்டி",
    "yacht": "படகு",
    "yeuse": "மரம்",
    "zebre": "வரிக்",
    "zeste": "தோல்",
    # More additions to ensure high accuracy
    "frere": "சகோதர",
    "soeur": "சகோதரி",
    "oncle": "மாமா",
    "tante": "அத்தை",
    "bague": "மோதிர",
    "perle": "முத்து",
    "boule": "பந்து",
    "cadre": "சட்டம்",
    "canne": "கோல்",
    "chale": "சால்",
    "creme": "கிரீம்",
    "dalle": "தரை",
    "datte": "பேரீச்",
    "dette": "கடன்",
    "digue": "அணை",
    "drame": "நாடக",
    "etage": "மாடி",
    "etang": "குளம்",
    "faute": "தவறு",
    "fibre": "நார்",
    "figue": "அத்தி",
    "films": "படம்",
    "flute": "புல்லா",
    "forme": "வடிவம்",
    "foule": "கூட்ட",
    "gants": "கையுறை",
}

# Create DataFrame
df = pd.DataFrame(list(french_tamil_dict.items()), columns=['french', 'tamil'])

# Save as CSV
df.to_csv('french_tamil_dataset.csv', index=False)

# Create vocabulary files
french_vocab = sorted(list(set(df['french'].values)))
tamil_vocab = sorted(list(set(df['tamil'].values)))

# Save vocabularies as pickle files
import pickle

with open('french_vocab.pkl', 'wb') as f:
    pickle.dump(french_vocab, f)

with open('tamil_vocab.pkl', 'wb') as f:
    pickle.dump(tamil_vocab, f)

print(f"Dataset created with {len(df)} word pairs")
print(f"French vocabulary size: {len(french_vocab)}")
print(f"Tamil vocabulary size: {len(tamil_vocab)}")